dbfilename redis_queue.rdb
dir /Users/pouyanshams/Desktop/iran-robota/backend/frappe-bench/config/pids
pidfile /Users/pouyanshams/Desktop/iran-robota/backend/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/pouyanshams/Desktop/iran-robota/backend/frappe-bench/config/redis_queue.acl
